//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VisionCollegeDSEDMarkingPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AchievedElement
    {
        public int AchevedID { get; set; }
        public Nullable<int> ResultFk { get; set; }
        public Nullable<int> MSOverviewFK { get; set; }
        public string AchievedItem { get; set; }
    
        public virtual MarkingScheduleOverview MarkingScheduleOverview { get; set; }
        public virtual Result Result { get; set; }
    }
}
