//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VisionCollegeDSEDMarkingPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssignmentSubmission
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AssignmentSubmission()
        {
            this.ModuleEnrollments = new HashSet<ModuleEnrollment>();
        }
    
        public int AssignmentSubmittedID { get; set; }
        public Nullable<System.DateTime> DateSubmitted { get; set; }
        public string LinkToFile { get; set; }
        public string Instructions { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ModuleEnrollment> ModuleEnrollments { get; set; }
    }
}
