//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VisionCollegeDSEDMarkingPortal.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class StudentPortalDBEntities2 : DbContext
    {
        public StudentPortalDBEntities2()
            : base("name=StudentPortalDBEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AchievedElement> AchievedElements { get; set; }
        public virtual DbSet<AssignmentSubmission> AssignmentSubmissions { get; set; }
        public virtual DbSet<MarkingOverviewTitle> MarkingOverviewTitles { get; set; }
        public virtual DbSet<MarkingScheduleOverview> MarkingScheduleOverviews { get; set; }
        public virtual DbSet<MarkingScheduleTable> MarkingScheduleTables { get; set; }
        public virtual DbSet<ModuleDetail> ModuleDetails { get; set; }
        public virtual DbSet<ModuleEnrollment> ModuleEnrollments { get; set; }
        public virtual DbSet<Result> Results { get; set; }
        public virtual DbSet<StudentDetail> StudentDetails { get; set; }
    }
}
