//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VisionCollegeDSEDMarkingPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MarkingScheduleOverview
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MarkingScheduleOverview()
        {
            this.AchievedElements = new HashSet<AchievedElement>();
        }
    
        public int MSOverviewID { get; set; }
        public Nullable<int> ModuleFK { get; set; }
        public Nullable<int> OverviewTitleFK { get; set; }
        public string CommentItem { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AchievedElement> AchievedElements { get; set; }
        public virtual MarkingOverviewTitle MarkingOverviewTitle { get; set; }
        public virtual ModuleDetail ModuleDetail { get; set; }
    }
}
