//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VisionCollegeDSEDMarkingPortal.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class ModuleDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ModuleDetail()
        {
            this.MarkingScheduleOverviews = new HashSet<MarkingScheduleOverview>();
            this.ModuleEnrollments = new HashSet<ModuleEnrollment>();
        }
    
        public int ModuleID { get; set; }
        [DisplayName("Module Code")]
        public string ModuleCode { get; set; }
        [DisplayName("Module Name")]
        public string ModuleName { get; set; }
        [DisplayName("Description")]
        public string ModuleDescription { get; set; }
        public string AssignmentFile { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MarkingScheduleOverview> MarkingScheduleOverviews { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ModuleEnrollment> ModuleEnrollments { get; set; }
    }
}
